platform :ios, '8.0'
use_frameworks!
target 'Universialshare' do 
pod 'AFNetworking', '~> 3.0' 
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDWebImage', '~>3.8'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'IQKeyboardManager'
pod 'MJRefresh'
pod 'ReactiveCocoa' ,'~>2.5'
pod 'SDCycleScrollView', '~> 1.64'
pod 'MJExtension'
pod 'FMDB'
pod 'UMengAnalytics-NO-IDFA'
end
